/**
 * @file    drv_button.h
 * @brief   Highly portable, fully decoupled button driver with Event Queue.
 * @note    Designed for cross-platform compatibility (Nuvoton, STM32, HT, GD32, etc.)
 * Uses a Ring Buffer to decouple hardware interrupts from application logic.
 */

#ifndef __DRV_BUTTON_H__
#define __DRV_BUTTON_H__

#include <stdint.h>

/* --- Timing Configuration --- */
#define BTN_TICK_MS         10      /**< Polling interval in ms */
#define BTN_DEBOUNCE_MS     20      /**< Debounce threshold in ms */
#define BTN_LONG_PRESS_MS   1000    /**< Long press threshold in ms */

#define BTN_DEBOUNCE_TICKS  (BTN_DEBOUNCE_MS / BTN_TICK_MS)
#define BTN_LONG_TICKS      (BTN_LONG_PRESS_MS / BTN_TICK_MS)

/* --- Event Definitions --- */
/**
 * @brief Button event types triggered by the state machine.
 */
typedef enum {
    BTN_EVENT_NONE = 0,
    BTN_EVENT_PRESS,                /**< Triggered immediately after debounce */
    BTN_EVENT_RELEASE,              /**< Triggered when the physical button is released */
    BTN_EVENT_SHORT_CLICK,          /**< Triggered upon release if duration < long press */
    BTN_EVENT_LONG_PRESS            /**< Triggered when press duration reaches long press threshold */
} btn_event_e;                      /* Changed to _e suffix to indicate enum type */

/* --- Message Queue Structure --- */
/**
 * @brief Event message structure used in the Ring Buffer.
 */
typedef struct {
    uint8_t     id;                 /**< The ID of the button that triggered the event */
    btn_event_e event;              /**< The type of event triggered */
} btn_msg_t;

/* --- Hardware Abstraction Callback --- */
/**
 * @brief  Function pointer type for reading physical pin state.
 * @param  port Generic port pointer (e.g., GPIOA, or NULL for Bit-band).
 * @param  pin  Generic pin value or address (e.g., GPIO_PIN_0, or Bit-band addr).
 * @retval 1 if the physical pin is High, 0 if Low.
 */
typedef uint8_t (*btn_hal_read_t)(void* port, uint32_t pin);

/* --- Button Object Structure --- */
/**
 * @brief Button object structure (Array-based management, Callback-free).
 */
typedef struct {
    uint8_t         id;             /**< Unique Button ID (User-defined) */
    
    /* Hardware binding */
    void* port;           /**< Generic Port (e.g., GPIOA, or NULL) */
    uint32_t        pin;            /**< Generic Pin (e.g., GPIO_PIN_0, or Bit-band address) */
    uint8_t         active_level;   /**< Trigger level: 0 for Active-Low, 1 for Active-High */
    
    /* Internal State Machine (Do NOT modify in application) */
    uint8_t         state;          /**< 0: Idle, 1: Pressed, 2: Long Pressed */
    uint16_t        tick_cnt;       /**< Timer tick counter */
} button_t;


/* ==============================================================================
 * Public APIs
 * ============================================================================== */

/**
 * @brief  Initialize the button driver and reset the internal event queue.
 * @note   Must be called once during system initialization before starting the timer.
 * @param  btn_array     Pointer to the user-defined button configuration array.
 * @param  count         Total number of elements in the button array.
 * @param  hal_read_func User-provided function to read the hardware pin state.
 * @retval None
 */
void Button_Init(button_t* btn_array, uint16_t count, btn_hal_read_t hal_read_func);

/**
 * @brief  Core state machine to process button debouncing and generate events.
 * @note   This function MUST be called periodically strictly at the interval 
 * defined by BTN_TICK_MS (e.g., every 10ms). It can be placed inside 
 * a Timer ISR or a precisely timed polling loop.
 * @retval None
 */
void Button_Ticks(void);

/**
 * @brief  Check if a specific button is currently in a logically pressed state (debounced).
 * @param  id The unique ID of the button you want to check.
 * @retval 1 if logically pressed, 0 if released or not found.
 */
uint8_t Button_Is_Pressed(uint8_t id);

/**
 * @brief  Returns a 32-bit mask representing the debounced state of ALL buttons.
 * @note   The bit position corresponds to the button's index in the initialization array.
 * (e.g., Bit 0 represents btn_array[0], Bit 1 represents btn_array[1]).
 * This is extremely useful for processing multi-key combinations (Combo Keys).
 * @retval 32-bit unsigned integer mask (1 = Pressed, 0 = Released).
 */
uint32_t Button_Get_State_Mask(void);

/**
 * @brief  Read and pop the oldest event from the button's internal ring buffer.
 * @note   This function should be called continuously in the main application loop 
 * to process events generated by the Button_Ticks() background process.
 * @param  msg Pointer to a user-provided btn_msg_t structure to store the popped event.
 * @retval 1 if an event was successfully read, 0 if the queue is empty.
 */
uint8_t Button_Read_Event(btn_msg_t* msg);

#endif /* __DRV_BUTTON_H__ */